import { Patient } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 1,
    salesforce_id: '003X000001abcde',
    first_name: 'Sarah',
    last_name: 'Mitchell',
    email: 'sarah.mitchell@email.com',
    phone: '(555) 123-4567',
    procedure_interest: 'LASIK',
    last_visit_date: '2025-11-15',
    consultation_notes: 'Patient expressed strong interest in LASIK. Main concern is night driving glare. Currently wears glasses for distance. Active lifestyle, plays tennis 3x/week. Wants procedure before vacation in March.',
    call_recording_summary: 'Patient called to ask about recovery time. Mentioned upcoming ski trip. Wants to know if she can drive at night immediately after LASIK.',
    engagement_score: 87,
    preferred_channel: 'email',
    created_at: '2025-10-01T10:30:00Z'
  },
  {
    id: 2,
    salesforce_id: '003X000001abcdf',
    first_name: 'Robert',
    last_name: 'Chen',
    email: 'robert.chen@email.com',
    phone: '(555) 234-5678',
    procedure_interest: 'Cataract',
    last_visit_date: '2025-12-10',
    consultation_notes: 'Cataract patient. Concerned about recovery time and ability to work after surgery. Prefers communication via SMS. Works in construction, needs to return to work quickly.',
    call_recording_summary: 'Patient asked about premium lens options and pricing. Interested in reducing dependence on reading glasses post-surgery.',
    engagement_score: 72,
    preferred_channel: 'sms',
    created_at: '2025-09-15T14:20:00Z'
  },
  {
    id: 3,
    salesforce_id: '003X000001abcdg',
    first_name: 'Maria',
    last_name: 'Garcia',
    email: 'maria.garcia@email.com',
    phone: '(555) 345-6789',
    procedure_interest: 'Premium Lens',
    last_visit_date: '2025-08-22',
    consultation_notes: 'Wellness check-up, discussed premium IOL options. Budget-conscious, asked about payment plans multiple times. Interested but hesitant.',
    call_recording_summary: 'Called to inquire about financing options. Asked if insurance covers any portion of premium lenses.',
    engagement_score: 34,
    preferred_channel: 'email',
    created_at: '2025-08-22T09:15:00Z'
  },
  {
    id: 4,
    salesforce_id: '003X000001abcdh',
    first_name: 'David',
    last_name: 'Thompson',
    email: 'david.thompson@email.com',
    phone: '(555) 456-7890',
    procedure_interest: 'LASIK',
    last_visit_date: '2025-10-28',
    consultation_notes: 'LASIK candidate, very active lifestyle. Marathon runner, surfer. Main concern is recovery time and when he can return to sports activities. Highly motivated.',
    call_recording_summary: 'Asked specific questions about UV protection post-LASIK and ocean water exposure during healing.',
    engagement_score: 91,
    preferred_channel: 'both',
    created_at: '2025-10-01T16:45:00Z'
  },
  {
    id: 5,
    salesforce_id: '003X000001abcdi',
    first_name: 'Jennifer',
    last_name: 'Williams',
    email: 'jennifer.williams@email.com',
    phone: '(555) 567-8901',
    procedure_interest: 'Cataract',
    last_visit_date: '2025-12-05',
    consultation_notes: 'Early-stage cataract patient. Not ready for surgery yet but wants to stay informed. Prefers email communication, asks detailed questions.',
    call_recording_summary: 'Inquired about how quickly cataracts typically progress and when surgery becomes medically necessary.',
    engagement_score: 58,
    preferred_channel: 'email',
    created_at: '2025-11-20T11:30:00Z'
  },
  {
    id: 6,
    salesforce_id: '003X000001abcdj',
    first_name: 'Michael',
    last_name: 'Anderson',
    email: 'michael.anderson@email.com',
    phone: '(555) 678-9012',
    procedure_interest: 'LASIK',
    last_visit_date: '2025-09-18',
    consultation_notes: 'Interested in LASIK but concerned about cost. Asked about payment plans and promotions. Works in tech, concerned about screen time post-procedure.',
    call_recording_summary: 'Patient called asking if there are any year-end promotions or special financing available.',
    engagement_score: 45,
    preferred_channel: 'sms',
    created_at: '2025-09-18T13:25:00Z'
  },
  {
    id: 7,
    salesforce_id: '003X000001abcdk',
    first_name: 'Lisa',
    last_name: 'Johnson',
    email: 'lisa.johnson@email.com',
    phone: '(555) 789-0123',
    procedure_interest: 'Premium Lens',
    last_visit_date: '2025-11-30',
    consultation_notes: 'Premium lens candidate for upcoming cataract surgery. Very detail-oriented, researched all options online before consultation. Wants the best technology available.',
    call_recording_summary: 'Asked about the difference between toric and multifocal lenses. Wants to eliminate both distance and reading glasses.',
    engagement_score: 82,
    preferred_channel: 'email',
    created_at: '2025-11-15T10:10:00Z'
  },
  {
    id: 8,
    salesforce_id: '003X000001abcdl',
    first_name: 'James',
    last_name: 'Martinez',
    email: 'james.martinez@email.com',
    phone: '(555) 890-1234',
    procedure_interest: 'LASIK',
    last_visit_date: '2025-10-12',
    consultation_notes: 'Young professional, wants LASIK to improve confidence and convenience. Wears contacts daily, experiencing dryness. Ready to schedule soon.',
    call_recording_summary: 'Confirmed appointment availability and asked about pre-surgery preparation requirements.',
    engagement_score: 76,
    preferred_channel: 'both',
    created_at: '2025-10-05T15:40:00Z'
  },
  {
    id: 9,
    salesforce_id: '003X000001abcdm',
    first_name: 'Patricia',
    last_name: 'Davis',
    email: 'patricia.davis@email.com',
    phone: '(555) 901-2345',
    procedure_interest: 'Cataract',
    last_visit_date: '2025-12-15',
    consultation_notes: 'Mature cataract patient, surgery recommended within 3 months. Medicare eligible. Concerned about choosing the right lens option.',
    call_recording_summary: 'Asked about recovery timeline and when she can resume gardening and reading.',
    engagement_score: 64,
    preferred_channel: 'email',
    created_at: '2025-12-01T09:50:00Z'
  },
  {
    id: 10,
    salesforce_id: '003X000001abcdn',
    first_name: 'Christopher',
    last_name: 'Brown',
    email: 'christopher.brown@email.com',
    phone: '(555) 012-3456',
    procedure_interest: 'LASIK',
    last_visit_date: '2025-11-08',
    consultation_notes: 'LASIK consultation, borderline candidate due to thin corneas. Discussed PRK as alternative. Needs follow-up testing before final decision.',
    call_recording_summary: 'Called to schedule additional corneal mapping appointment. Wants to explore all options.',
    engagement_score: 68,
    preferred_channel: 'sms',
    created_at: '2025-11-01T14:15:00Z'
  }
];
