import type {
  CampaignTemplate,
  Campaign,
  ContentVariant,
  DeliveryEntry,
  AnalyticsMetric,
  DashboardStats,
  DailySummary,
  AgentActivity,
} from '../types';

export const mockTemplates: CampaignTemplate[] = [
  {
    id: 1,
    name: 'LASIK Year-End Promotion',
    type: 'promotional',
    target_procedure: 'LASIK',
    base_prompt: 'Promotional campaign for LASIK procedures targeting consultation patients.',
    email_subject_template: 'Special Offer: LASIK Starting at ${pricing}',
    cadence_config: [
      { day: 1, channel: 'email' },
      { day: 3, channel: 'sms' },
      { day: 5, channel: 'email' },
      { day: 7, channel: 'sms' },
    ],
    created_at: '2026-04-01T10:00:00Z',
  },
  {
    id: 2,
    name: 'Cataract Education Series',
    type: 'educational',
    target_procedure: 'Cataract',
    base_prompt: 'Educational campaign for cataract patients with informative content.',
    email_subject_template: 'Understanding Your Cataract Treatment Options',
    cadence_config: [
      { day: 1, channel: 'email' },
      { day: 7, channel: 'email' },
      { day: 14, channel: 'sms' },
    ],
    created_at: '2026-03-15T10:00:00Z',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    template_id: 1,
    name: 'Summer LASIK Promo 2026',
    status: 'in_review',
    date_range_start: '2026-04-15',
    date_range_end: '2026-08-31',
    prompt_text:
      'Run a year-end LASIK promotion for all consultation patients who haven\'t converted, with pricing starting at $500/eye, running through August 31st',
    parsed_prompt_params: {
      campaign_name: 'Summer LASIK Promo',
      target: 'LASIK patients, engagement > 70',
      date_range: 'April 15 — August 31, 2026',
      recipients: 20,
      cadence: 'Email (Day 1) → SMS (Day 3) → Email (Day 5) → SMS (Day 7)',
    },
    recipient_count: 20,
    template_name: 'LASIK Year-End Promotion',
    created_at: '2026-04-05T14:30:00Z',
    updated_at: '2026-04-05T14:35:00Z',
  },
  {
    id: 2,
    template_id: 2,
    name: 'Cataract Awareness Q2',
    status: 'active',
    date_range_start: '2026-04-01',
    date_range_end: '2026-06-30',
    prompt_text: 'Educational campaign for cataract patients with informative content about treatment options',
    parsed_prompt_params: {
      campaign_name: 'Cataract Awareness Q2',
      target: 'Cataract patients',
      date_range: 'April 1 — June 30, 2026',
      recipients: 7,
      cadence: 'Email (Day 1) → Email (Day 7) → SMS (Day 14)',
    },
    recipient_count: 7,
    template_name: 'Cataract Education Series',
    created_at: '2026-03-28T10:00:00Z',
    updated_at: '2026-04-01T09:00:00Z',
  },
];

export const mockVariants: ContentVariant[] = [
  {
    id: 1,
    campaign_id: 1,
    patient_id: 1,
    patient_name: 'Sarah Mitchell',
    message_type: 'email',
    tone_label: 'Medical/Professional',
    subject_line: 'Your LASIK Consultation Follow-Up',
    content:
      'Dear Sarah,\n\nThank you for your recent consultation regarding LASIK vision correction. Based on your examination, you are an excellent candidate for this procedure.\n\nWe are pleased to offer a special promotional rate of $500 per eye, available through August 31st, 2026. This represents significant savings while maintaining our commitment to exceptional care and outcomes.\n\nTo schedule your procedure or discuss any questions, please contact our office at your earliest convenience.\n\nSincerely,\nDr. Johnson and the nVision Team',
    is_selected: false,
    created_at: '2026-04-05T14:35:00Z',
  },
  {
    id: 2,
    campaign_id: 1,
    patient_id: 1,
    patient_name: 'Sarah Mitchell',
    message_type: 'email',
    tone_label: 'Friendly',
    subject_line: 'Great News About Your LASIK Journey, Sarah!',
    content:
      'Hi Sarah,\n\nWe loved meeting you at your LASIK consultation! Your eyes are in great shape for the procedure, and we think you\'re going to love your results.\n\nHere\'s some exciting news: we\'re running a special promotion — just $500 per eye through the end of August. It\'s the perfect time to finally say goodbye to glasses and contacts!\n\nReady to take the next step? Give us a call, and we\'ll get you scheduled. We can\'t wait to help you see the world more clearly!\n\nWarm regards,\nThe nVision Team',
    is_selected: true,
    created_at: '2026-04-05T14:35:00Z',
  },
  {
    id: 3,
    campaign_id: 1,
    patient_id: 1,
    patient_name: 'Sarah Mitchell',
    message_type: 'email',
    tone_label: 'Empathetic',
    subject_line: 'We Understand Your Vision Concerns, Sarah',
    content:
      'Dear Sarah,\n\nWe know that considering LASIK is a big decision, and we appreciate you trusting us with your vision care journey.\n\nYou mentioned during your consultation that you\'re tired of the hassle of contacts and glasses. We truly understand how limiting that can feel, and we\'re here to help you achieve the freedom you\'re looking for.\n\nTo make this easier, we\'re offering a special rate of $500 per eye through August 31st. We want to ensure that cost isn\'t a barrier to the vision you deserve.\n\nWhenever you\'re ready to move forward, we\'re here to support you every step of the way.\n\nWith care,\nDr. Johnson and the nVision Team',
    is_selected: false,
    created_at: '2026-04-05T14:35:00Z',
  },
  {
    id: 4,
    campaign_id: 1,
    patient_id: 2,
    patient_name: 'David Thompson',
    message_type: 'email',
    tone_label: 'Friendly',
    subject_line: 'Your LASIK Opportunity, David!',
    content:
      'Hi David,\n\nThanks for coming in to explore LASIK with us! After reviewing your exam, you\'re a perfect candidate for the procedure.\n\nWe have a limited-time offer: $500 per eye through August 31st. This is a great chance to invest in clearer vision at a fantastic price.\n\nLet\'s get you scheduled! Call us anytime, and we\'ll find a time that works for you.\n\nBest,\nThe nVision Team',
    is_selected: true,
    created_at: '2026-04-05T14:35:00Z',
  },
  {
    id: 5,
    campaign_id: 1,
    patient_id: 3,
    patient_name: 'Emily Rodriguez',
    message_type: 'email',
    tone_label: 'Informative',
    subject_line: 'LASIK Information and Special Pricing',
    content:
      'Hello Emily,\n\nFollowing your consultation, we wanted to provide you with key information about LASIK:\n\n• Recovery time: Most patients return to normal activities within 24-48 hours\n• Success rate: Over 96% of patients achieve 20/20 vision or better\n• Procedure duration: Approximately 10-15 minutes per eye\n• Current pricing: $500 per eye (through August 31st, 2026)\n\nIf you have any questions or would like to schedule your procedure, please contact our office.\n\nBest regards,\nnVision Surgical Center',
    is_selected: true,
    created_at: '2026-04-05T14:35:00Z',
  },
];

export const mockDeliveryLog: DeliveryEntry[] = [
  {
    id: 1,
    campaign_recipient_id: 1,
    channel: 'email',
    sent_at: '2026-04-05T09:00:00Z',
    tracking_id: 'trk_email_001',
    status: 'opened',
    patient_name: 'Sarah Mitchell',
    campaign_name: 'Summer LASIK Promo 2026',
    content_preview: 'Great News About Your LASIK Journey, Sarah!',
  },
  {
    id: 2,
    campaign_recipient_id: 2,
    channel: 'sms',
    sent_at: '2026-04-05T09:05:00Z',
    tracking_id: 'trk_sms_001',
    status: 'delivered',
    patient_name: 'David Thompson',
    campaign_name: 'Summer LASIK Promo 2026',
    content_preview: 'Hi David, special LASIK pricing through Aug 31st...',
  },
  {
    id: 3,
    campaign_recipient_id: 3,
    channel: 'email',
    sent_at: '2026-04-05T09:10:00Z',
    tracking_id: 'trk_email_002',
    status: 'clicked',
    patient_name: 'Emily Rodriguez',
    campaign_name: 'Summer LASIK Promo 2026',
    content_preview: 'LASIK Information and Special Pricing',
  },
  {
    id: 4,
    campaign_recipient_id: 4,
    channel: 'email',
    sent_at: '2026-04-04T14:00:00Z',
    tracking_id: 'trk_email_003',
    status: 'sent',
    patient_name: 'Michael Chen',
    campaign_name: 'Cataract Awareness Q2',
    content_preview: 'Understanding Your Cataract Treatment Options',
  },
  {
    id: 5,
    campaign_recipient_id: 5,
    channel: 'email',
    sent_at: '2026-04-04T14:05:00Z',
    tracking_id: 'trk_email_004',
    status: 'opened',
    patient_name: 'Jennifer Park',
    campaign_name: 'Cataract Awareness Q2',
    content_preview: 'Learn about advanced cataract surgery options...',
  },
  {
    id: 6,
    campaign_recipient_id: 6,
    channel: 'sms',
    sent_at: '2026-04-04T10:00:00Z',
    tracking_id: 'trk_sms_002',
    status: 'failed',
    patient_name: 'Robert Turner',
    campaign_name: 'Cataract Awareness Q2',
    content_preview: 'Hi Robert, learn about your cataract options...',
  },
  {
    id: 7,
    campaign_recipient_id: 7,
    channel: 'email',
    sent_at: '2026-04-03T16:00:00Z',
    tracking_id: 'trk_email_005',
    status: 'opened',
    patient_name: 'Amanda White',
    campaign_name: 'Cataract Awareness Q2',
    content_preview: 'Cataract Surgery: What to Expect',
  },
];

export const mockAnalytics: AnalyticsMetric[] = [
  {
    id: 1,
    campaign_id: 1,
    metric_date: '2026-04-05',
    emails_sent: 15,
    emails_opened: 12,
    emails_clicked: 8,
    sms_sent: 5,
    sms_replied: 2,
    conversions: 3,
  },
  {
    id: 2,
    campaign_id: 1,
    metric_date: '2026-04-04',
    emails_sent: 10,
    emails_opened: 7,
    emails_clicked: 4,
    sms_sent: 3,
    sms_replied: 1,
    conversions: 1,
  },
  {
    id: 3,
    campaign_id: 2,
    metric_date: '2026-04-05',
    emails_sent: 5,
    emails_opened: 4,
    emails_clicked: 2,
    sms_sent: 2,
    sms_replied: 1,
    conversions: 1,
  },
  {
    id: 4,
    campaign_id: 2,
    metric_date: '2026-04-04',
    emails_sent: 4,
    emails_opened: 3,
    emails_clicked: 1,
    sms_sent: 0,
    sms_replied: 0,
    conversions: 0,
  },
  {
    id: 5,
    campaign_id: 2,
    metric_date: '2026-04-03',
    emails_sent: 3,
    emails_opened: 2,
    emails_clicked: 1,
    sms_sent: 0,
    sms_replied: 0,
    conversions: 0,
  },
];

export const mockDashboardStats: DashboardStats = {
  total_patients: 50,
  active_campaigns: 1,
  pending_review: 1,
  total_sent: 27,
  total_opened: 20,
  total_clicked: 12,
  total_conversions: 5,
  open_rate: '74%',
  click_rate: '44%',
};

export const mockDailySummaries: DailySummary[] = [
  {
    id: 1,
    campaign_id: 1,
    report_date: '2026-04-05',
    summary_text:
      'Summer LASIK Promo shows strong early performance with 80% open rate and 3 conversions in the first 24 hours. Top performers: Sarah Mitchell (clicked, scheduled consultation), Emily Rodriguez (clicked, requested pricing info). Recommendation: Continue current cadence, consider SMS follow-up for unopened emails after Day 3.',
    created_at: '2026-04-05T18:00:00Z',
  },
  {
    id: 2,
    campaign_id: 2,
    report_date: '2026-04-04',
    summary_text:
      'Cataract Awareness Q2 maintaining steady engagement. Educational content resonating well with target demographic (60+ age group). Michael Chen and Jennifer Park showing high engagement. Next steps: Schedule follow-up touchpoint for Day 7 as per cadence plan.',
    created_at: '2026-04-04T18:00:00Z',
  },
];

export const mockAgentActivity: AgentActivity[] = [
  {
    id: 1,
    campaign_id: 1,
    agent_name: 'Data Analyst',
    activity_message: 'Querying Salesforce for matching patients...',
    status: 'completed',
    created_at: '2026-04-05T14:30:00Z',
  },
  {
    id: 2,
    campaign_id: 1,
    agent_name: 'Data Analyst',
    activity_message: 'Found 20 patients matching criteria',
    status: 'completed',
    created_at: '2026-04-05T14:30:05Z',
  },
  {
    id: 3,
    campaign_id: 1,
    agent_name: 'Copywriter',
    activity_message: 'Generating personalized content with 5 tone variations...',
    status: 'completed',
    created_at: '2026-04-05T14:30:07Z',
  },
  {
    id: 4,
    campaign_id: 1,
    agent_name: 'Copywriter',
    activity_message: 'Content ready for review',
    status: 'completed',
    created_at: '2026-04-05T14:30:12Z',
  },
  {
    id: 5,
    campaign_id: 1,
    agent_name: 'Campaign Manager',
    activity_message: 'Building blended email+SMS delivery schedule...',
    status: 'completed',
    created_at: '2026-04-05T14:30:14Z',
  },
  {
    id: 6,
    campaign_id: 1,
    agent_name: 'Campaign Manager',
    activity_message: '4-week cadence set — 20 emails + 12 SMS scheduled',
    status: 'completed',
    created_at: '2026-04-05T14:30:18Z',
  },
];

export const mockRecipients = [
  {
    id: 1,
    patient_id: 1,
    patient_name: 'Sarah Mitchell',
    email_opened: true,
    clicked: true,
    sms_replied: false,
    status: 'converted',
  },
  {
    id: 2,
    patient_id: 2,
    patient_name: 'David Thompson',
    email_opened: true,
    clicked: false,
    sms_replied: true,
    status: 'engaged',
  },
  {
    id: 3,
    patient_id: 3,
    patient_name: 'Emily Rodriguez',
    email_opened: true,
    clicked: true,
    sms_replied: false,
    status: 'converted',
  },
  {
    id: 4,
    patient_id: 4,
    patient_name: 'Michael Chen',
    email_opened: false,
    clicked: false,
    sms_replied: false,
    status: 'not_opened',
  },
];
